### ISSUE TITLE
Ajout d'un getLegend sur les sources compatibles

### ISSUE THREAD

**Issue by RovenThur** [GisOsTeam/aol#9]
Ajouter une méthode getLegend qui renvoie soit une base 64, soit une url sur les sources compatibles.

Je pense notamment à TileWMS, ImageWMS et ImageArcGISRest

**Comment by mathieumast** [comment]
Il faut que se soit un object complexe du type: 
Array<{
label: string;
b64image: string;
height: number;
width: number;
}>

**Comment by RovenThur** [comment]
Ok mais pour les WMS on peut faire la même chose ?
